from selenium.webdriver.common.by import By

search_type = {
    'xpath': By.XPATH,
    'tag_name': By.TAG_NAME,
    'id': By.ID
}

movie_list = [
        "American Dreamz",
        "Animal Factory",
        "Aurora Borealis",
        "Baadasssss!",
        "The Ballad of Little Jo",
        "Better than Sex",
        "The Big Hit",
        "Blood and Wine",
        "Brick",
        "Brothers",
        "Bubba Ho-Tep",
        "Career Girls",
        "Casanova",
        "Chop Shop",
        "Citizen Ruth",
        "Connie and Carla",
        "C.R.A.Z.Y",
        "Criminal",
        "Crush",
        "Dark Days",
        "The Dead Girl",
        "The Devil's Backbone",
        "Diamond Men",
        "Dick",
        "The Dinner Game",
        "Dinner Rush",
        "The Dish",
        "Teacher's Pet",
        "The Door in the Floor",
        "Driving Lessons",
        "Duck Season",
        "East is East",
        "Everything Put Together",
        "Fast, Cheap and Out of Control",
        "15 Minutes",
        "Find Me Guilty",
        "Firelight",
        "Following",
        "Gilles' Wife",
        "Gloomy Sunday",
        "Go Tigers!",
        "Going in Style",
        "The Great Buck Howard",
        "The Greatest Game Ever Played",
        "The Hard Word",
        "The Harmonists",
        "Hedwig and the Angry Inch",
        "Hidalgo",
        "A Home at the End of the World",
        "The House of Sand",
        "How to Lose Friends & Alienate People",
        "I Served the King of England",
        "Idiocracy",
        "In the Shadow of the Moon",
        "Indigenes",
        "Innocent Blood",
        "Intermission",
        "Island in the Sky",
        "Julia",
        "Keeping Mum",
        "Kill Me Later",
        "King of California",
        "The King of Masks",
        "King of the Hill",
        "Kontroll",
        "Las Ciudad",
        "La Petite Lili",
        "La Promesse",
        "Lady for a Day",
        "The Last Shot",
        "Lawless Heart",
        "Levity",
        "Look Both Ways",
        "The Lookout",
        "Love and Death On Long Island",
        "Mad Money",
        "The Maltese Falcon",
        "The Man from Elysian Fields",
        "Man Push Cart",
        "Marvin's Room",
        "The Matador",
        "Matchstick Men",
        "Matewan",
        "Maybe Baby",
        "The Merry Gentleman",
        "Metroland",
        "A Midnight Clear",
        "The Mighty",
        "Millions",
        "Mirrormask",
        "Moonlighting",
        "Mountains of the Moon",
        "Mrs. Palfrey at the Claremont",
        "My First Mister",
        "The Mystery of Picasso",
        "Nine Lives",
        "Nothing But the Truth",
        "October Sky",
        "Off the Map",
        "Once Were Warriors",
        "One Fine Day",
        "Owning Mahowny",
        "The Painted Veil",
        "Paradise Now",
        "Peter's Friends",
        "Phoebe in Wonderland",
        "The Pledge",
        "Priceless",
        "Prisoner of Paradise",
        "The Prize Winner of Defiance, Ohio",
        "Queen of Hearts",
        "Quinceanera",
        "Raising Victor Vargas",
        "Resurrecting the Champ",
        "Resurrection",
        "Safe Men",
        "Scarecrow",
        "Seven Men from Now",
        "Shadowboxer",
        "Something New",
        "Son of Rambow",
        "Songcatcher",
        "Spring Forward",
        "Starting Out in the Evening",
        "Startup.com",
        "State of the Union",
        "The Steel Helmet",
        "Still Crazy",
        "Stone Reader",
        "Sweet Land",
        "The Tao of Steve",
        "Taste of Cherry",
        "The Third Miracle",
        "Thumbsucker",
        "Tristram Shandy: A Cock and Bull Story",
        "Tumbleweeds",
        "Tuvalu",
        "The TV Set",
        "Two Family House",
        "Two Lovers",
        "Walking the Dead",
        "The Weather Man",
        "Welcome to Sarajevo",
        "Went to Coney Island on a Mission from God… Be Back by Five",
        "What Doesn’t Kill You",
        "The Whole Wide World",
        "The Wide Blue Road",
        "Winter Solstice",
        "Word Wars",
        "The World's Fastest Indian",
        "Zathura: A Space Adventure",
]